### PR TITLE
(PUP-5215) Build OpenSSL 1.0.0s with safer default cert dir

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
screen shot 2015-09-17 at 2 50 09 pm

**Comment by melissa** [comment]
cc/ @joshcooper @shrug

**Comment by melissa** [comment]
Run on Windows 2003 i386

**Comment by joshcooper** [comment]
:+1:

**Comment by melissa** [comment]
Closing this in favor of the update to Ruby 2.1.7 and OpenSSL 1.0.2d

**Pull request closed without merging**
