### PR TITLE
(RE-6194) Build 1.9.3 against openssl 1.0.2e

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by shermdog** [comment]
Does it saying 1.9.1 every mean there is a problem?

**Comment by underscorgan** [comment]
Testing at http://jenkins-release.delivery.puppetlabs.net/job/puppet-msi-2016-01-06-16-03-25-12fce74

**Comment by underscorgan** [comment]
@shermdog nope, that's expected

**Comment by underscorgan** [comment]
screen shot 2016-01-06 at 4 27 37 pm

**Comment by McdonaldSeanp** [comment]
:+1:

**Pull request merged**
