### PR TITLE
(RE-5287) Update Rubygems to 2.4.5.1 to fix 'gem install nokogiri' (x64)

### PR DESCRIPTION
**Pull request by geoffnichols**
Ruby 2.1's Rubygems has a bug where gem does not download
correct gemfiles for (Windows) MinGW platforms. This bug
prevents Rubygems from installing upstream's precompiled
Nokogiri gems.

This commit patches Ruby 2.1.7's vendored Rubygems to 2.4.5.1,
which appears to fix the Rubygems bug. (Please see
http://www.nokogiri.org/tutorials/installing_nokogiri.html#windows
for more details.)

### CODE REVIEW

**Comment by shrug** [comment]
:+1:

**Comment by geoffnichols** [comment]
ping @Iristyle

**Comment by ferventcoder** [comment]
~~~
C:\code\puppetinstallers>where ruby
c:\Program Files\Puppet Labs\Puppet\sys\ruby\bin\ruby.exe

C:\code\puppetinstallers>ruby --version
ruby 2.1.7p400 (2015-08-18 revision 51632) [x64-mingw32]

C:\code\puppetinstallers>gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
deep_merge (1.0.1)
ffi (1.9.6 x64-mingw32)
io-console (0.4.3, 0.4.2)
json (1.8.1)
minitar (0.5.4)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
stomp (1.3.3)
test-unit (2.1.7.0, 2.1.6.0, 2.1.5.0)
win32-dir (0.4.9)
win32-eventlog (0.6.2)
win32-process (0.7.4)
win32-security (0.2.5)
win32-service (0.8.6)

C:\code\puppetinstallers>gem install nokogiri
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Fetching: nokogiri-1.6.6.2-x64-mingw32.gem (100%)
Nokogiri is built with the packaged libraries: libxml2-2.9.2, libxslt-1.1.28, zl
ib-1.2.8, libiconv-1.14.
Successfully installed nokogiri-1.6.6.2-x64-mingw32
Parsing documentation for mini_portile-0.6.2
Installing ri documentation for mini_portile-0.6.2
Parsing documentation for nokogiri-1.6.6.2-x64-mingw32
Installing ri documentation for nokogiri-1.6.6.2-x64-mingw32
Done installing documentation for mini_portile, nokogiri after 2 seconds
2 gems installed
~~~

**Comment by ferventcoder** [comment]
:+1:

**Comment by ferventcoder** [comment]
I did this with irb, but I liked how pry showed the results better so:
~~~
C:\code\puppetinstallers>gem install pry
Fetching: method_source-0.8.2.gem (100%)
Successfully installed method_source-0.8.2
Fetching: slop-3.6.0.gem (100%)
Successfully installed slop-3.6.0
Fetching: coderay-1.1.0.gem (100%)
Successfully installed coderay-1.1.0
Fetching: pry-0.10.3.gem (100%)
Successfully installed pry-0.10.3
Parsing documentation for method_source-0.8.2
Installing ri documentation for method_source-0.8.2
Parsing documentation for slop-3.6.0
Installing ri documentation for slop-3.6.0
invalid options: -SNw2
(invalid options are ignored)
Parsing documentation for coderay-1.1.0
Installing ri documentation for coderay-1.1.0
Parsing documentation for pry-0.10.3
Installing ri documentation for pry-0.10.3
Done installing documentation for method_source, slop, coderay, pry after 7 seco
nds
4 gems installed

C:\code\puppetinstallers>pry
[1] pry(main)> require 'nokogiri'iri'
=> true
[2] pry(main)> require 'open-uri'
=> true
[3] pry(main)> doc = Nokogiri::HTML(open('http://www.nokogiri.org/tutorials/inst
alling_nokogiri.html'))=> #(Document:0x181c990 {s/installing_nokogiri.html'))
  name = "document",
  children = [
    #(DTD:0x181535c { name = "html" }),
    #(Comment "[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <!
[endif]"),
    #(Comment "[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]
"),
    #(Comment "[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]"),
    #(Comment "[if gt IE 8]><!"),
    #(Element:0x147ae68 {
      name = "html",
      attributes = [ #(Attr:0x1447900 { name = "class", value = "no-js" })],
      children = [
        #(Text " "),
        #(Comment "<![endif]"),
        #(Text "\n\n  \n    \n  "),
        #(Element:0xef2c20 {
          name = "head",
          children = [
            #(Text "\n    "),
            #(Element:0x1cdf978 {
              name = "meta",
              attributes = [
                #(Attr:0x1cc8d2c { name = "charset", value = "utf-8" })]
              }),
            #(Text "\n    "),
            #(Element:0x1c922f4 {
              name = "meta",
              attributes = [
                #(Attr:0x1c8b8f0 {
                  name = "http-equiv",
                  value = "X-UA-Compatible"
                  }),
                #(Attr:0x1c8b8dc {
                  name = "content",
                  value = "IE=edge,chrome=1"
~~~

**Comment by Iristyle** [comment]
Same comment - re:binaries here @geoffnichols

**Comment by geoffnichols** [comment]
To ensure this is repeatable, we're patching Rubygems with our Rubyinstaller fork. 

See https://github.com/puppetlabs/rubyinstaller/pull/37 for the updates to our Rubyinstaller fork.

The update of this branch used `rsync -avW ruby-2.1.7-x64-mingw32/ ~/repos/puppet-win32-ruby/ruby/` with the artifact from http://jenkins-release.delivery.puppetlabs.net/view/Windows%20Builds/job/WindowsRubyBuilds/111/.

**Comment by Iristyle** [comment]
So @geoffnichols - I'm not sure if you're still working on it... but it would be nice to do one of the following:

* Update binaries in a separate PR, given they must have changed for some reason (I'm pretty sure it was not in response to just bumping the rubygems version)... 
* Update the commit messages on these PRs to indicate why the binaries changed.


I would be more in favor of the former rather than the latter... just so that for historical reasons, we have a solid record of what the binary changes were around for.

FWIW - in the rubyinstaller PR you mentioned (https://github.com/puppetlabs/rubyinstaller/pull/37), I only see changes to Ruby code, and not C code that would have been compiled differently.

**Comment by geoffnichols** [comment]
Thanks @Iristyle. I updated the commit to exclude any changed binary (`.a`, `.dll`, `.exe`, `.so`) files.

**Comment by joshcooper** [comment]
@Iristyle we're currently tracking 2.1.7.0 tags: https://github.com/puppetlabs/puppet-agent/blob/stable/configs/components/windows_ruby.json#L4-L5, so you'll need to update puppet-agent to either track the branch, verify fixes are working, then tag PFTW and bump puppet-agent. Or if you're confident about the fixes, just tag & bump versions.

**Comment by ferventcoder** [comment]
@joshcooper I'll handle this aspect.

**Pull request merged**
