### PR TITLE
(re-3700) Update to openssl 1.0.0q for multiple CVEs

### PR DESCRIPTION
**Pull request by shrug**
Fixes for https://www.openssl.org/news/secadv_20150108.txt

### CODE REVIEW

**Comment by melissa** [comment]
:+1: it looks good to me, and a lot cleaner than when I last updated it :)

**Comment by ferventcoder** [comment]
Will this need targeted at 2.1.x branches?

**Comment by shrug** [comment]
We will need to update, yes. Is there a release scheduled for a package w/2.1.5?

We have an open discussion on the team regarding openssl direction - ie, do we want to stay with 1.0.0 for a while or move to a later release, and what timeframe that should happen.

**Comment by ferventcoder** [comment]
I'm guessing this was discussed @Iristyle @shrug ... I'll let that be a discussion in the ticket that was created. :)

**Pull request merged**
