### PR TITLE
(RE-5287) Update Rubygems to 2.4.5.1 to fix 'gem install nokogiri' (x86)

### PR DESCRIPTION
**Pull request by geoffnichols**
Ruby 2.1's Rubygems has a bug where gem does not download
correct gemfiles for (Windows) MinGW platforms. This bug
prevents Rubygems from installing upstream's precompiled
Nokogiri gems.

This commit patches Ruby 2.1.7's vendored Rubygems to 2.4.5.1,
which appears to fix the Rubygems bug. (Please see
http://www.nokogiri.org/tutorials/installing_nokogiri.html#windows
for more details.)

### CODE REVIEW

**Comment by shrug** [comment]
:+1:

**Comment by geoffnichols** [comment]
ping @Iristyle

**Comment by Iristyle** [comment]
I don't quite understand why we ended up with binaries changing in here?

**Comment by geoffnichols** [comment]
To ensure this is repeatable, we're patching Rubygems with our Rubyinstaller fork. 

See https://github.com/puppetlabs/rubyinstaller/pull/37 for the updates to our Rubyinstaller fork.

The update of this branch used `rsync -avW ruby-2.1.7-i386-mingw32/  ~/repos/puppet-win32-ruby/ruby/` with the artifact from http://jenkins-release.delivery.puppetlabs.net/view/Windows%20Builds/job/WindowsRubyBuilds/111/.

**Comment by geoffnichols** [comment]
Update the commit to exclude any changed binary (`.a`, `.dll`, `.exe`, `.so`) files.

**Comment by ferventcoder** [comment]
As mentioned on the other ticket, a tag will need to be added for the updated fixes. https://github.com/puppetlabs/puppet-win32-ruby/pull/122#issuecomment-155147898

**Pull request merged**
