### PR TITLE
(PUP-7528) Add Ruby 2.4.1 (64-bit)

### PR DESCRIPTION
**Pull request by Magisus**
This is Ruby 2.4.1 built by vanagon for 64-bit Windows

### CODE REVIEW

**Comment by Magisus** [comment]
So something is wrong here, but I'm not sure what. A bunch of these files had no changed content, but they have `100644 → 100755`. What does that mean and how do I fix it? (Google was unhelpful)

**Comment by Magisus** [comment]
This seems more correct, I imagine the larger diff might simply be the result of the changing Y version.

**Comment by Iristyle** [comment]
Hmmm.. 4599 files changed for 64-bit and 4601 files changed for 32-bit.

Where did you base the branches? (plausibly they could be based off 2.3 branches to generate less churn here if they're not already)

**Comment by Magisus** [comment]
That is what I did.

**Comment by Iristyle** [comment]
Would you be able to compare the gems from 2.3 up to this 2.4 PR?
https://github.com/puppetlabs/puppet-win32-ruby/tree/2.3.x-x64/ruby/lib/ruby/gems/2.3.0/gems

Just to get an idea if any versions changed, etc.

Would also be good to trigger a `ci:test:git` run with a hacked up copy of the Puppet pre-suite against `win-10-ent-i386` vmpooler image for 32-bit and `win-2012r2-x86_64` vmpooler image for 64-bit, like:

```
GEM_SOURCE=http://rubygems.delivery.puppetlabs.net/ TEST_TARGET=windows2012r2-64a PUPPET_FORK='Iristyle' bundle exec rake ci:test:git SHA=`git lastref`
```

**Comment by Magisus** [comment]
Test output from `ci:test:git` on windows2012r2-64a:
```
      Test Suite: tests @ 2017-05-19 12:00:09 -0700

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 4420.43 seconds
      Average Test Time: 13.16 seconds
              Attempted: 336
                 Passed: 272
                 Failed: 6
                Errored: 4
                Skipped: 53
                Pending: 1
                  Total: 336

      - Specific Test Case Status -
```

**Comment by Iristyle** [comment]
Ok, so looking through the failures and errors and cross-checking them vs https://github.com/puppetlabs/puppet/pull/5781#issuecomment-300375179:

* F - Test Case ./tests/ensure_puppet-agent_paths.rb
    * standard fail for ci:test:git
* F - Test Case ./tests/language/server_set_facts.rb
    * `CFPropertyList` 2.2.8 is being dragged in from the Facter 2.4.6 gem via `CFPropertyList ~> 2.2.6` - it's have some Ruby 2.4 fixes in 2.3.5 and to get them will require shipping a new Facter 2.5 gem with an updated dependency - see also [PA-668](https://tickets.puppetlabs.com/browse/PA-668) and [PUP-6596](https://tickets.puppetlabs.com/browse/PUP-6596)
* F - Test Case ./tests/lookup/config5_interpolation.rb
    * standard fail for ci:test:git
* F - Test Case ./tests/lookup/v3_config_and_data.rb
    * standard fail for ci:test:git
* F - Test Case ./tests/lookup/v4_hieradata_with_v5_configs.rb
    * standard fail for ci:test:git
* F - Test Case ./tests/windows/env_windows_installdir_fact.rb
    * standard fail for ci:test:git

* E - Test Case ./tests/agent/agent_parses_json_catalog.rb
    * looks like a connnection refused sort of anomaly - doesn't look related to Ruby 2.4
* E - Test Case ./tests/node/check_woy_cache_works.rb
    * haven't seen this one before, but looks like another environment sort of problem specific to ci:test:git
* E - Test Case ./tests/lookup/hiera3_custom_backend.rb
    * standard fail for ci:test:git
* E - Test Case ./tests/resource/file/ticket_6448_file_with_utf8_source.rb
    * this looks like a legit Unicode failure... which could plausibly be related to Ruby 2.4 - will have to look into that later, but I don't think it should hold up merging this PR

**Comment by Iristyle** [comment]
I don't see any reason to not merge this - going for it.

**Pull request merged**
