### PR TITLE
(RE-5538) Update OpenSSL to include a safer default cert dir

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by haus** [comment]
@melissa can you dos2unix these please to reduce the line number noise.

**Comment by melissa** [comment]
@haus dos2unix removed the file differences

**Comment by haus** [comment]
:+1: now @melissa do you want to ticket adding dos2unix as a post build step for rubyinstaller?

**Comment by melissa** [comment]
@haus RE-5558

**Comment by mckern** [comment]
Nothing scary here.

clowns

**Pull request merged**
