### PR TITLE
(RE-5359) Update Ruby to 2.1.7 with OpenSSL 1.0.2d

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by haus** [comment]
Conflicts!

**Comment by melissa** [comment]
I ran dos2unix on these files, which is why you see entire files highlighted as change, but not apparent difference between the old and new

**Comment by haus** [comment]
:+1:

**Comment by melissa** [comment]
screen shot 2015-09-18 at 8 55 07 am

run on windows 2012 x86_64 vmpooler image

**Comment by joshcooper** [comment]
:+1: though I thought we had already run dos2unix on everything in the repo?

**Comment by melissa** [comment]
The previous PR was merged before I had a chance to do that

**Pull request merged**
