### PR TITLE
(PUP-5215) Build OpenSSL 1.0.0s with safer default cert dir

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
screen shot 2015-09-17 at 2 17 24 pm

**Comment by melissa** [comment]
cc/ @joshcooper @shrug

**Comment by melissa** [comment]
Run on Windows 2003 i386

**Comment by joshcooper** [comment]
the screen shot shows the old DEFAULT_CONFIG_FILE directory, wrong screen shot?

**Comment by melissa** [comment]
shoot, I glazed over that. Not the wrong screen shot. Still broken :(

**Comment by melissa** [comment]
maybe we should just skip any more openssl 1.0.0 releases for windows and stick with 1.0.2 from now on...

**Comment by melissa** [comment]
Closing this in favor of the update to Ruby 2.1.7 and OpenSSL 1.0.2d

**Pull request closed without merging**
