### PR TITLE
(RE-4104) Allow vendored gems to failback to use Ruby on %PATH%

### PR DESCRIPTION
**Pull request by geoffnichols**
This commit includes the patches from PUP-4077. To facilitate
CI using multiple versions of Ruby managed with Pik, this
allows our vendored gems to failback to using a Ruby that
exists on %PATH%, but only if Ruby is not available at %~dp0 first.

### CODE REVIEW

**Comment by rji** [comment]
:+1:

**Comment by Iristyle** [comment]
Same extraneous mode noise -- I'll try and fix it during merge.

**Comment by rji** [comment]
@Iristyle I'm :+1: on this if the mode changes can be ignored.

**Comment by Iristyle** [comment]
Merged w/out extraneous mode changes - tagged as `2.0.0.3-x64`

**Pull request closed without merging**
